[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Disable secrets scanning - PUBLIC_CLERK_PUBLISHABLE_KEY is meant to be public
# It's designed to be exposed in client-side JavaScript
[build.processing.secrets]
  enabled = false
