[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Exclude dist folder from secrets scanning
# PUBLIC_CLERK_PUBLISHABLE_KEY is meant to be in client-side code
[build.processing.secrets]
  enabled = true
  omit_paths = ["dist/**/*"]
