[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # Disable secrets scanning - PUBLIC_CLERK_PUBLISHABLE_KEY is meant to be public
  SECRETS_SCAN_ENABLED = "false"
